---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: java-maven
  name: java-maven
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: java-maven
    spec:
      containers:
      - image: ryanduah/private-app:jma-actions
        name: java-maven
        ports:
        - name: java-maven
          containerPort: 8080  
      imagePullSecrets:
        - name: docker-registry-secret 

---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: java-maven
  name: java-maven
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: java-maven